// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SheetMusic.Api.Database;

namespace SheetMusic.Api.Migrations
{
    [DbContext(typeof(SheetMusicContext))]
    [Migration("20200813201119_Added borrowd columns")]
    partial class Addedborrowdcolumns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SheetMusic.Api.Database.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SheetMusic.Api.Database.Entities.MusicPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Indexable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MusicParts");
                });

            modelBuilder.Entity("SheetMusic.Api.Database.Entities.MusicPartAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("MusicPartId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MusicPartId");

                    b.ToTable("MusicPartAliases");
                });

            modelBuilder.Entity("SheetMusic.Api.Database.Entities.Musician", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("UserGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserGroupId");

                    b.ToTable("Musicians");
                });

            modelBuilder.Entity("SheetMusic.Api.Database.Entities.MusicianMusicPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MusicPartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MusicianId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MusicPartId");

                    b.HasIndex("MusicianId");

                    b.ToTable("MusicianMusicPart");
                });

            modelBuilder.Entity("SheetMusic.Api.Database.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("SheetMusic.Api.Database.Entities.ProjectSheetMusicSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SheetMusicSetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SheetMusicSetId");

                    b.ToTable("ProjectSheetMusicSets");
                });

            modelBuilder.Entity("SheetMusic.Api.Database.Entities.SheetMusicCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SheetMusicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SheetMusicSetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SheetMusicSetId");

                    b.ToTable("SheetMusicCategories");
                });

            modelBuilder.Entity("SheetMusic.Api.Database.Entities.SheetMusicPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MusicPartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MusicPartId");

                    b.HasIndex("SetId");

                    b.ToTable("SheetMusicParts");
                });

            modelBuilder.Entity("SheetMusic.Api.Database.Entities.SheetMusicSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ArchiveNumber")
                        .HasColumnType("int");

                    b.Property<string>("Arranger")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("BorrowedDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("BorrowedFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Composer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasBeenScanned")
                        .HasColumnType("bit");

                    b.Property<string>("MissingParts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordingUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoleSellingAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SheetMusicSets");
                });

            modelBuilder.Entity("SheetMusic.Api.Database.Entities.UserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("SheetMusic.Api.Database.Entities.MusicPartAlias", b =>
                {
                    b.HasOne("SheetMusic.Api.Database.Entities.MusicPart", "MusicPart")
                        .WithMany("Aliases")
                        .HasForeignKey("MusicPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SheetMusic.Api.Database.Entities.Musician", b =>
                {
                    b.HasOne("SheetMusic.Api.Database.Entities.UserGroup", "UserGroup")
                        .WithMany("Musicians")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SheetMusic.Api.Database.Entities.MusicianMusicPart", b =>
                {
                    b.HasOne("SheetMusic.Api.Database.Entities.MusicPart", "MusicPart")
                        .WithMany("MusicianMusicParts")
                        .HasForeignKey("MusicPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SheetMusic.Api.Database.Entities.Musician", "Musician")
                        .WithMany("MusicianMusicParts")
                        .HasForeignKey("MusicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SheetMusic.Api.Database.Entities.ProjectSheetMusicSet", b =>
                {
                    b.HasOne("SheetMusic.Api.Database.Entities.Project", "Project")
                        .WithMany("SetConnections")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SheetMusic.Api.Database.Entities.SheetMusicSet", "Set")
                        .WithMany("ProjectConnections")
                        .HasForeignKey("SheetMusicSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SheetMusic.Api.Database.Entities.SheetMusicCategory", b =>
                {
                    b.HasOne("SheetMusic.Api.Database.Entities.Category", "Category")
                        .WithMany("SheetMusicCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SheetMusic.Api.Database.Entities.SheetMusicSet", "SheetMusicSet")
                        .WithMany("Categories")
                        .HasForeignKey("SheetMusicSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SheetMusic.Api.Database.Entities.SheetMusicPart", b =>
                {
                    b.HasOne("SheetMusic.Api.Database.Entities.MusicPart", "Part")
                        .WithMany("Parts")
                        .HasForeignKey("MusicPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SheetMusic.Api.Database.Entities.SheetMusicSet", "Set")
                        .WithMany("Parts")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
