using MediatR;
using SheetMusic.Api.Sets.Services;
using System.IO.Compression;
using System.Text.Json;

namespace SheetMusic.Api.Sets.Commands;

/// <summary>
/// Splits a combined score PDF into part PDFs using OCR-detected page headers.
/// </summary>
public sealed class SplitPartsPdf(Stream pdfContent) : IRequest<SplitPartsPdfResult>
{
    /// <summary>
    /// The combined score PDF.
    /// </summary>
    public Stream PdfContent { get; } = pdfContent;

    /// <summary>
    /// Handles PDF splitting and packages the parts with a review manifest.
    /// </summary>
    public sealed class Handler(PdfPartSplitter splitter) : IRequestHandler<SplitPartsPdf, SplitPartsPdfResult>
    {
        /// <inheritdoc />
        public async Task<SplitPartsPdfResult> Handle(SplitPartsPdf request, CancellationToken cancellationToken)
        {
            var split = await splitter.SplitAsync(request.PdfContent, cancellationToken);
            await using var archiveContent = new MemoryStream();
            using (var archive = new ZipArchive(archiveContent, ZipArchiveMode.Create, leaveOpen: true))
            {
                var manifestGroups = new List<SplitPartsPdfManifestGroup>();
                foreach (var group in split.Groups)
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    var fileName = $"{GetSafeFileName(group.NormalizedPartName)}.pdf";
                    var entry = archive.CreateEntry(fileName, CompressionLevel.Optimal);
                    await using var entryStream = entry.Open();
                    await entryStream.WriteAsync(group.Content!, cancellationToken);
                    manifestGroups.Add(new SplitPartsPdfManifestGroup(fileName, group.NormalizedPartName, group.StartPage, group.EndPage, group.Confidence, group.Diagnostic));
                }

                var manifest = archive.CreateEntry("review-manifest.json", CompressionLevel.Optimal);
                await using var manifestStream = manifest.Open();
                await JsonSerializer.SerializeAsync(manifestStream, new SplitPartsPdfManifest(manifestGroups, split.Diagnostics), cancellationToken: cancellationToken);
            }

            return new SplitPartsPdfResult(archiveContent.ToArray());
        }

        private static string GetSafeFileName(string value)
        {
            var safeName = string.Concat(value.Select(character => char.IsLetterOrDigit(character) || character is ' ' or '-' or '_' ? character : '_')).Trim();
            return string.IsNullOrWhiteSpace(safeName) ? "UNRECOGNIZED" : safeName;
        }
    }
}

/// <summary>
/// Contains the ZIP archive generated by <see cref="SplitPartsPdf"/>.
/// </summary>
public sealed record SplitPartsPdfResult(byte[] Content);

/// <summary>
/// Describes the contents of the generated part archive.
/// </summary>
public sealed record SplitPartsPdfManifest(IReadOnlyList<SplitPartsPdfManifestGroup> Groups, IReadOnlyList<PdfPartSplitDiagnostic> Diagnostics);

/// <summary>
/// Describes one generated PDF in the review manifest.
/// </summary>
public sealed record SplitPartsPdfManifestGroup(string FileName, string PartName, int StartPage, int EndPage, double Confidence, string DetectionMethod);